[package]
name = "preinterpret"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["David Edey <github@david-edey.com>"]
description = "An intuitive toolkit to simplify code generation development"
repository = "https://github.com/dhedey/preinterpret"
keywords = ["macros", "declarative-macros", "toolkit", "interpreter", "preprocessor"]
# Categories have to come from https://crates.io/category_slugs
# And whilst there's a development-tools::procedural-macro-helpers, there's no declarative macro category.
categories = ["development-tools", "compilers"]
# MSRV 1.56.0 is the start of Edition 2021
# MSRV 1.61.0 is the old MSRV of syn
# MRSV 1.63.0 is needed to support RefMut::filter_map
# MRSV 1.68.0 is the new latest MSRV of syn (as of syn 2.0.107 released on 19th October 2025)
# MRSV 1.71.0 is the new latest MSRV of unicode-ident (released on 8th February 2026)
# If changing this, also update the local-check-msrv.sh script and ci.yml
rust-version = "1.71"

[lib]
proc-macro = true

[[bench]]
name = "basic"
harness = false
required-features = ["benchmark"]

[features]
benchmark = [] # For internal use only
debug = [] # Non-stable, for internal use only

[dependencies]
proc-macro2 = { version = "1.0.93" }
syn = { version = "2.0.107", default-features = false, features = ["parsing", "derive", "printing", "clone-impls", "full"] }
quote = { version = "1.0.38", default-features = false }
slotmap = { version = "1.0.7" }

[dev-dependencies]
trybuild = { version = "1.0.110", features = ["diff"] }
